name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
      - run: ruby test/smoke_test.rb
      - run: ruby test/eporner_test.rb
      - run: ruby test/tpdb_test.rb
      - run: ruby test/stashdb_test.rb
